export const GET_WEATHER_LOCATIONS_EPIC = 'GET_WEATHER_LOCATIONS_EPIC';
export const GET_WEATHER_LOCATIONS_SUCCESS = 'GET_WEATHER_LOCATIONS_SUCCESS';
export const GET_WEATHER_LOCATIONS_ERROR = 'GET_WEATHER_LOCATIONS_ERROR';
export const GET_WEATHER_LOCATIONS_LOADING = 'GET_WEATHER_LOCATIONS_LOADING';
export const GET_WEATHER_LOCATIONS_CANCEL = 'GET_WEATHER_LOCATIONS_CANCEL';

export const GET_WEATHER_LOCATIONS_INFO_EPIC =
  'GET_WEATHER_LOCATIONS_INFO_EPIC';
export const GET_WEATHER_LOCATIONS_INFO_SUCCESS =
  'GET_WEATHER_LOCATIONS_INFO_SUCCESS';
export const GET_WEATHER_LOCATIONS_INFO_ERROR =
  'GET_WEATHER_LOCATIONS_INFO_ERROR';
export const GET_WEATHER_LOCATIONS_INFO_LOADING =
  'GET_WEATHER_LOCATIONS_INFO_LOADING';
export const GET_WEATHER_LOCATIONS_INFO_CANCEL =
  'GET_WEATHER_LOCATIONS_INFO_CANCEL';
