export const GET_WEATHER_LOCATIONS_EPIC = 'GET_WEATHER_LOCATIONS_EPIC';
export const GET_WEATHER_LOCATIONS_SUCCESS = 'GET_WEATHER_LOCATIONS_SUCCESS';
export const GET_WEATHER_LOCATIONS_ERROR = 'GET_WEATHER_LOCATIONS_ERROR';
export const GET_WEATHER_LOCATIONS_LOADING = 'GET_WEATHER_LOCATIONS_LOADING';
export const GET_WEATHER_LOCATIONS_CANCEL = 'GET_WEATHER_LOCATIONS_CANCEL';
