export const GET_HOME_DATA_EPIC = 'GET_HOME_DATA_EPIC';
export const GET_HOME_DATA_SUCCESS = 'GET_HOME_DATA_SUCCESS';
export const GET_HOME_DATA_ERROR = 'GET_HOME_DATA_ERROR';
export const GET_HOME_DATA_LOADING = 'GET_HOME_DATA_LOADING';
export const GET_HOME_DATA_CANCEL = 'GET_HOME_DATA_CANCEL';

export const GET_WEATHER_LOCATIONS_EPIC = 'GET_WEATHER_LOCATIONS_EPIC';
export const GET_WEATHER_LOCATIONS_SUCCESS = 'GET_WEATHER_LOCATIONS_SUCCESS';
export const GET_WEATHER_LOCATIONS_ERROR = 'GET_WEATHER_LOCATIONS_ERROR';
export const GET_WEATHER_LOCATIONS_LOADING = 'GET_WEATHER_LOCATIONS_LOADING';
export const GET_WEATHER_LOCATIONS_CANCEL = 'GET_WEATHER_LOCATIONS_CANCEL';
